Assigning 450 genomes to PopPUNK clusters...
First few files:
Burkholderia_pseudomallei_134K_GCF_009830075.1_Thailand.fasta
Burkholderia_pseudomallei_134_GCF_009830095.1_Thailand.fasta
Burkholderia_pseudomallei_1701_GCF_003268105.1_Viet_Nam.fasta
Burkholderia_pseudomallei_2002721684_GCF_002110925.1_USA_Texas.fasta
Burkholderia_pseudomallei_2002734728_GCF_002111105.1_USA_California.fasta
PopPUNK (POPulation Partitioning Using Nucleotide Kmers)
	(with backend: sketchlib v2.1.1
	 sketchlib: /opt/conda/envs/poppunk-env/lib/python3.10/site-packages/pp_sketchlib.cpython-310-x86_64-linux-gnu.so)

Graph-tools OpenMP parallelisation enabled: with 48 threads
Mode: Using previous model with a reference database

Traceback (most recent call last):
  File "/opt/conda/envs/poppunk-env/bin/poppunk", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/envs/poppunk-env/lib/python3.10/site-packages/PopPUNK/__main__.py", line 471, in main
    model = loadClusterFit(model_prefix + "/" + os.path.basename(model_prefix) + '_fit.pkl',
  File "/opt/conda/envs/poppunk-env/lib/python3.10/site-packages/PopPUNK/models.py", line 102, in loadClusterFit
    with open(pkl_file, 'rb') as pickle_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'poppunk_db/poppunk_db_fit.pkl'
